### PR TITLE
fix crash due to obj_gmlive being git ignored + fix array comparisions

### PR DESCRIPTION
**Pull request by raf13lol**
yeah

### CODE REVIEW

**Comment by raf13lol** [comment]
some people might not have obj_gmlive

**Comment by raf13lol** [comment]
ill make it a variable hold on

**Comment by raf13lol** [comment]
hold on

**Comment by raf13lol** [comment]
this fixes `help speed` giving something like "aliases are \`\`"

**Comment by Reycko** [comment]
Yea

**Pull request merged**
